apiVersion: apps/v1
kind: Deployment
metadata:
  name: eliza-app
  namespace: mongodb
  labels:
    app: eliza-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eliza-app
  template:
    metadata:
      labels:
        app: eliza-app
    spec:
      containers:
      - name: eliza-app
        image: quay.io/chatton/eliza
        imagePullPolicy: Always
        env:
          - name: CONNECTION_STRING
            value: mongodb://eliza:my-password@my-rs-0.my-rs-svc.mongodb.svc.cluster.local:27017,my-rs-1.my-rs-svc.mongodb.svc.cluster.local:27017,my-rs-2.my-rs-svc.mongodb.svc.cluster.local:27017/?replicaSet=my-rs&authSource=admin&authMechanism=SCRAM-SHA-256

---
apiVersion: v1
kind: Service
metadata:
  name: eliza-app
spec:
  type: NodePort
  selector:
    app: eliza-app
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 32000

